
name: MicroToDo-UI Pipeline

on: workflow_dispatch
  # push:
  #   branches:
  #     - main
  #     - releases/**

  
jobs:
  build: 
    name: demo job
    runs-on: ubuntu-latest
    steps: 
    -  name: checkout
       uses: actions/checkout@v6.0.1
        
    -   name: greetings
        run: echo "Hi i am hero"
